/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package my.swift;

import java.awt.Desktop;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import static java.nio.file.StandardCopyOption.*;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import javax.swing.JPopupMenu;
import javax.swing.JOptionPane;

/**
 *
 * @author sebch
 */
public class swiftUI extends javax.swing.JFrame {

    private static final SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd-HH-mm-ss");

    /**
     * Creates new form swiftUI
     */
    public swiftUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu18 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuBar4 = new java.awt.MenuBar();
        menu7 = new java.awt.Menu();
        menu8 = new java.awt.Menu();
        menuBar5 = new java.awt.MenuBar();
        menu9 = new java.awt.Menu();
        menu10 = new java.awt.Menu();
        jMenu20 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu23 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenuItem53 = new javax.swing.JMenuItem();
        jMenuItem63 = new javax.swing.JMenuItem();
        jMenu34 = new javax.swing.JMenu();
        jMenuItem75 = new javax.swing.JMenuItem();
        jMenuItem87 = new javax.swing.JMenuItem();
        popupMenu1 = new java.awt.PopupMenu();
        menuBar6 = new java.awt.MenuBar();
        menu11 = new java.awt.Menu();
        menu12 = new java.awt.Menu();
        menuBar7 = new java.awt.MenuBar();
        menu13 = new java.awt.Menu();
        menu14 = new java.awt.Menu();
        jMenuItem89 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenuItem47 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem49 = new javax.swing.JMenuItem();
        jMenuItem50 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem51 = new javax.swing.JMenuItem();
        jMenuItem52 = new javax.swing.JMenuItem();
        jMenuItem54 = new javax.swing.JMenuItem();
        jMenuItem55 = new javax.swing.JMenuItem();
        jMenuItem56 = new javax.swing.JMenuItem();
        jMenuItem57 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem59 = new javax.swing.JMenuItem();
        jMenuItem60 = new javax.swing.JMenuItem();
        jMenuItem61 = new javax.swing.JMenuItem();
        jMenuItem62 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem58 = new javax.swing.JMenuItem();
        jMenuItem64 = new javax.swing.JMenuItem();
        jMenuItem65 = new javax.swing.JMenuItem();
        jMenuItem66 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem67 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu32 = new javax.swing.JMenu();
        jMenuItem68 = new javax.swing.JMenuItem();
        jMenu33 = new javax.swing.JMenu();
        jMenuItem69 = new javax.swing.JMenuItem();
        jMenu35 = new javax.swing.JMenu();
        jMenuItem70 = new javax.swing.JMenuItem();
        jMenu36 = new javax.swing.JMenu();
        jMenuItem71 = new javax.swing.JMenuItem();
        jMenu37 = new javax.swing.JMenu();
        jMenuItem72 = new javax.swing.JMenuItem();
        jMenuItem73 = new javax.swing.JMenuItem();
        jMenuItem74 = new javax.swing.JMenuItem();
        jMenuItem76 = new javax.swing.JMenuItem();
        jMenuItem77 = new javax.swing.JMenuItem();
        jMenu38 = new javax.swing.JMenu();
        jMenuItem78 = new javax.swing.JMenuItem();
        jMenu39 = new javax.swing.JMenu();
        jMenuItem79 = new javax.swing.JMenuItem();
        jMenuItem80 = new javax.swing.JMenuItem();
        jMenuItem81 = new javax.swing.JMenuItem();
        jMenuItem82 = new javax.swing.JMenuItem();
        jMenu40 = new javax.swing.JMenu();
        jMenuItem83 = new javax.swing.JMenuItem();
        jMenuItem85 = new javax.swing.JMenuItem();
        jMenuItem84 = new javax.swing.JMenuItem();
        jMenuItem86 = new javax.swing.JMenuItem();
        jMenuItem88 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu26 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu27 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu28 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenu29 = new javax.swing.JMenu();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenu30 = new javax.swing.JMenu();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenu31 = new javax.swing.JMenu();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenu41 = new javax.swing.JMenu();
        jMenu42 = new javax.swing.JMenu();
        jMenu43 = new javax.swing.JMenu();
        jMenu44 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu18.setText("File");
        jMenuBar4.add(jMenu18);

        jMenu19.setText("Edit");
        jMenuBar4.add(jMenu19);

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        menu7.setLabel("File");
        menuBar4.add(menu7);

        menu8.setLabel("Edit");
        menuBar4.add(menu8);

        menu9.setLabel("File");
        menuBar5.add(menu9);

        menu10.setLabel("Edit");
        menuBar5.add(menu10);

        jMenu20.setText("jMenu20");

        jMenu21.setText("jMenu21");

        jMenuItem13.setText("jMenuItem13");

        jMenuItem14.setText("jMenuItem14");

        jMenu22.setText("jMenu22");

        jMenu23.setText("File");
        jMenuBar5.add(jMenu23);

        jMenu24.setText("Edit");
        jMenuBar5.add(jMenu24);

        jMenuItem15.setText("jMenuItem15");

        jMenuItem24.setText("jMenuItem24");

        jMenuItem42.setText("jMenuItem42");

        jMenuItem43.setText("jMenuItem43");

        jMenuItem53.setText("jMenuItem53");

        jMenuItem63.setText("jMenuItem63");

        jMenu34.setText("jMenu34");

        jMenuItem75.setText("jMenuItem75");

        jMenuItem87.setText("jMenuItem87");

        popupMenu1.setLabel("popupMenu1");

        menu11.setLabel("File");
        menuBar6.add(menu11);

        menu12.setLabel("Edit");
        menuBar6.add(menu12);

        menu13.setLabel("File");
        menuBar7.add(menu13);

        menu14.setLabel("Edit");
        menuBar7.add(menu14);

        jMenuItem89.setText("jMenuItem89");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setBackground(new java.awt.Color(255, 51, 51));
        jMenuBar1.setForeground(new java.awt.Color(255, 51, 51));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jMenu1.setText("Setup");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("SG");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jMenu10.setText("SWIFT");

        jMenuItem2.setText("MT103");
        jMenuItem2.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenuItem2MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem2);

        jMenuItem3.setText("MT202");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem3);

        jMenuItem4.setText("MT499");
        jMenu10.add(jMenuItem4);

        jMenuItem5.setText("MT700");
        jMenu10.add(jMenuItem5);

        jMenuItem6.setText("MT730");
        jMenu10.add(jMenuItem6);

        jMenuItem7.setText("MT734");
        jMenu10.add(jMenuItem7);

        jMenuItem8.setText("MT740");
        jMenu10.add(jMenuItem8);

        jMenuItem9.setText("MT742");
        jMenu10.add(jMenuItem9);

        jMenuItem10.setText("MT750");
        jMenu10.add(jMenuItem10);

        jMenuItem11.setText("MT799");
        jMenu10.add(jMenuItem11);

        jMenuItem12.setText("MT999");
        jMenu10.add(jMenuItem12);

        jMenu2.add(jMenu10);

        jMenu12.setText("MEPS");

        jMenuItem45.setText("ACK");
        jMenu12.add(jMenuItem45);

        jMenuItem46.setText("MT103");
        jMenuItem46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem46ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem46);

        jMenuItem47.setText("MT202");
        jMenu12.add(jMenuItem47);

        jMenu2.add(jMenu12);

        jMenu11.setText("KOFAX");

        jMenuItem48.setText("MT798");
        jMenu11.add(jMenuItem48);

        jMenu2.add(jMenu11);

        jMenu13.setText("ECPS");

        jMenuItem49.setText("202_ENQUIRY");
        jMenu13.add(jMenuItem49);

        jMenuItem50.setText("203_ENQUIRY");
        jMenu13.add(jMenuItem50);

        jMenu2.add(jMenu13);

        jMenu14.setText("BV");

        jMenuItem51.setText("BG AMENDMENT");
        jMenu14.add(jMenuItem51);

        jMenuItem52.setText("BG APPLICATION");
        jMenu14.add(jMenuItem52);

        jMenuItem54.setText("IB SETTLEMENT");
        jMenu14.add(jMenuItem54);

        jMenuItem55.setText("LC SETTLEMENT");
        jMenu14.add(jMenuItem55);

        jMenuItem56.setText("LC AMENDMENT");
        jMenu14.add(jMenuItem56);

        jMenuItem57.setText("LC APPLICATION");
        jMenuItem57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem57ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem57);

        jMenu2.add(jMenu14);

        jMenu15.setText("SIBS CIF");

        jMenuItem59.setText("CIF ENQUIRY 1603 REQUEST");
        jMenu15.add(jMenuItem59);

        jMenuItem60.setText("CIF ENQUIRY 1608 REQUEST");
        jMenu15.add(jMenuItem60);

        jMenuItem61.setText("CIF ENQUIRY 1612 REQUEST");
        jMenu15.add(jMenuItem61);

        jMenuItem62.setText("CIF UPDATE REQUEST");
        jMenu15.add(jMenuItem62);

        jMenu2.add(jMenu15);

        jMenu16.setText("SIBS DDA");

        jMenuItem58.setText("DDA ENQUIRY REQUEST (LCY)");
        jMenu16.add(jMenuItem58);

        jMenuItem64.setText("DDA ENQUIRY REQUEST (FCY)");
        jMenu16.add(jMenuItem64);

        jMenuItem65.setText("DDA UPDATE REQUEST (LCY)");
        jMenu16.add(jMenuItem65);

        jMenuItem66.setText("DDA UPDATE REQUEST (LCY)");
        jMenuItem66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem66ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem66);

        jMenu2.add(jMenu16);

        jMenu17.setText("AML");

        jMenuItem67.setText("INFAL101");
        jMenu17.add(jMenuItem67);

        jMenu2.add(jMenu17);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("MY");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jMenu32.setText("AML-ENAMECHECK");

        jMenuItem68.setText("INFAL401");
        jMenu32.add(jMenuItem68);

        jMenu7.add(jMenu32);

        jMenu33.setText("FX MATCHING");

        jMenuItem69.setText("FX MATCHING REQUEST");
        jMenu33.add(jMenuItem69);

        jMenu7.add(jMenu33);

        jMenu35.setText("IPS/RENTAS");

        jMenuItem70.setText("IPS/RENTAS REQUEST");
        jMenu35.add(jMenuItem70);

        jMenu7.add(jMenu35);

        jMenu36.setText("KOFAX");

        jMenuItem71.setText("MT798");
        jMenu36.add(jMenuItem71);

        jMenu7.add(jMenu36);

        jMenu37.setText("SIBS CIF");

        jMenuItem72.setText("CIF ENQUIRY 1603 REQUEST");
        jMenu37.add(jMenuItem72);

        jMenuItem73.setText("CIF ENQUIRY 1608 REQUEST");
        jMenu37.add(jMenuItem73);

        jMenuItem74.setText("CIF ENQUIRY 1612 REQUEST");
        jMenu37.add(jMenuItem74);

        jMenuItem76.setText("CIF UPDATE REQUEST");
        jMenu37.add(jMenuItem76);

        jMenuItem77.setText("CIF REQUEST");
        jMenu37.add(jMenuItem77);

        jMenu7.add(jMenu37);

        jMenu38.setText("SIBS CLS");

        jMenuItem78.setText("CLS REQUEST");
        jMenu38.add(jMenuItem78);

        jMenu7.add(jMenu38);

        jMenu39.setText("SIBS DDA");

        jMenuItem79.setText("ENQUIRY (LCY) REQUEST");
        jMenu39.add(jMenuItem79);

        jMenuItem80.setText("ENQUIRY (FCY) REQUEST");
        jMenu39.add(jMenuItem80);

        jMenuItem81.setText("UPDATE (LCY) REQUEST");
        jMenu39.add(jMenuItem81);

        jMenuItem82.setText("UPDATE (LCY) REQUEST");
        jMenu39.add(jMenuItem82);

        jMenu7.add(jMenu39);

        jMenu40.setText("SWIFT");

        jMenuItem83.setText("103");
        jMenu40.add(jMenuItem83);

        jMenuItem85.setText("202");
        jMenu40.add(jMenuItem85);

        jMenuItem84.setText("734");
        jMenu40.add(jMenuItem84);

        jMenuItem86.setText("799");
        jMenu40.add(jMenuItem86);

        jMenuItem88.setText("999");
        jMenu40.add(jMenuItem88);

        jMenu7.add(jMenu40);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("CN");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jMenu25.setText("AML-ENAMECHECK");

        jMenuItem16.setText("INFAL401");
        jMenu25.add(jMenuItem16);

        jMenu8.add(jMenu25);

        jMenu26.setText("ECPS");

        jMenuItem17.setText("202_ENQUIRY");
        jMenu26.add(jMenuItem17);

        jMenuItem18.setText("203_ENQUIRY");
        jMenu26.add(jMenuItem18);

        jMenu8.add(jMenu26);

        jMenu27.setText("ICP");

        jMenuItem19.setText("ICP007");
        jMenu27.add(jMenuItem19);

        jMenuItem20.setText("ICP008");
        jMenu27.add(jMenuItem20);

        jMenuItem21.setText("ICP009");
        jMenu27.add(jMenuItem21);

        jMenu8.add(jMenu27);

        jMenu28.setText("REACH");

        jMenuItem22.setText("101_UPDATE");
        jMenu28.add(jMenuItem22);

        jMenuItem23.setText("102_CREATE");
        jMenu28.add(jMenuItem23);

        jMenuItem25.setText("102_DELETE");
        jMenu28.add(jMenuItem25);

        jMenuItem26.setText("102_UPDATE");
        jMenu28.add(jMenuItem26);

        jMenuItem27.setText("103_ENQUIRY");
        jMenu28.add(jMenuItem27);

        jMenuItem28.setText("104_ENQUIRY");
        jMenu28.add(jMenuItem28);

        jMenu8.add(jMenu28);

        jMenu29.setText("SIBS CIF");

        jMenuItem29.setText("CIF ENQUIRY 1603 REQUEST");
        jMenu29.add(jMenuItem29);

        jMenuItem30.setText("CIF ENQUIRY 1608 REQUEST");
        jMenu29.add(jMenuItem30);

        jMenuItem31.setText("CIF ENQUIRY 1612 REQUEST");
        jMenu29.add(jMenuItem31);

        jMenuItem32.setText("CIF UPDATE REQUEST");
        jMenu29.add(jMenuItem32);

        jMenu8.add(jMenu29);

        jMenu30.setText("SIBS DDA");

        jMenuItem33.setText("ENQUIRY (LCY) REQUEST");
        jMenu30.add(jMenuItem33);

        jMenuItem34.setText("ENQUIRY (FCY) REQUEST");
        jMenu30.add(jMenuItem34);

        jMenuItem35.setText("UPDATE (LCY) REQUEST");
        jMenu30.add(jMenuItem35);

        jMenuItem36.setText("UPDATE (FCY) REQUEST");
        jMenu30.add(jMenuItem36);

        jMenu8.add(jMenu30);

        jMenu31.setText("SWIFT OUTGOING");

        jMenuItem37.setText("202");
        jMenu31.add(jMenuItem37);

        jMenuItem38.setText("400");
        jMenu31.add(jMenuItem38);

        jMenuItem39.setText("734");
        jMenu31.add(jMenuItem39);

        jMenuItem40.setText("756");
        jMenu31.add(jMenuItem40);

        jMenuItem41.setText("799");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        jMenu31.add(jMenuItem41);

        jMenuItem44.setText("999");
        jMenuItem44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem44ActionPerformed(evt);
            }
        });
        jMenu31.add(jMenuItem44);

        jMenu8.add(jMenu31);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("HK");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jMenu41.setText("SIBS DDA");
        jMenu9.add(jMenu41);

        jMenu42.setText("SIBS CIF");
        jMenu9.add(jMenu42);

        jMenu43.setText("SWIFT");
        jMenu9.add(jMenu43);

        jMenu44.setText("ECPS");
        jMenu9.add(jMenu44);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1276, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try {
            Desktop desktop = null;
            if (Desktop.isDesktopSupported()) {
                desktop = Desktop.getDesktop();
            }
            desktop.open(new File("C:\\Users\\sebch\\Desktop\\"));
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private Path getParentPath() {
        String workingDir = System.getProperty("user.dir");
        Path p1 = Paths.get(workingDir);
        System.out.println(p1.getParent());
        return p1.getParent();
    }

    private int addMessage(File file, Timestamp timestamp) {
        try {
            FileInputStream fis = new FileInputStream(file);
            BufferedReader br = new BufferedReader(new FileReader(file));
            String result = "";
            String line = "";
            while ((line = br.readLine()) != null) {
                result = result + line;
            }

            result = "Message Content: \r\n" + result;
            result = "Message ID: \r\n" + result;
            result = "Queue Manager: \r\n" + result;
            result = "Time: " + sdf.format(timestamp).toString() + "\r\n" + result;
            file.delete();
            FileOutputStream fos = new FileOutputStream(file);
            fos.write(result.getBytes());
            fos.flush();
        } catch (IOException e) {

            e.printStackTrace();

        }
        return 1;

    }


    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Path parentPath = getParentPath();
        try {
            Desktop desktop = null;
            if (Desktop.isDesktopSupported()) {
                desktop = Desktop.getDesktop();
            }
            desktop.open(new File(parentPath.toString() + "/templates/SG_SWIFT_MT202.txt"));
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "Click OK when completed", "Click OK when completed", JOptionPane.CLOSED_OPTION);
        BufferedWriter bw = null;
        FileWriter fw = null;
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        File source = new File(parentPath.toString() + "/templates/SG_SWIFT_MT202.txt");
        File dest = new File(parentPath.toString() + "/logs/SG_SWIFT_MT202" + sdf.format(timestamp).toString() + ".txt");
        try {

            Files.copy(source.toPath(), dest.toPath());
            File mFile = new File(parentPath.toString() + "/logs/SG_SWIFT_MT202" + sdf.format(timestamp).toString() + ".txt");
            int completion = addMessage(mFile, timestamp);
            if (completion == 1) {
                System.out.println("Done");
            }
        } catch (IOException e) {

            e.printStackTrace();

        } finally {

            try {

                if (bw != null) {
                    bw.close();
                }

                if (fw != null) {
                    fw.close();
                }

            } catch (IOException ex) {

                ex.printStackTrace();

            }

        }


    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenuItem2MenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MenuKeyPressed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem41ActionPerformed

    private void jMenuItem44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem44ActionPerformed

    private void jMenuItem46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem46ActionPerformed

    private void jMenuItem57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem57ActionPerformed

    private void jMenuItem66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem66ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(swiftUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(swiftUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(swiftUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(swiftUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new swiftUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu36;
    private javax.swing.JMenu jMenu37;
    private javax.swing.JMenu jMenu38;
    private javax.swing.JMenu jMenu39;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu40;
    private javax.swing.JMenu jMenu41;
    private javax.swing.JMenu jMenu42;
    private javax.swing.JMenu jMenu43;
    private javax.swing.JMenu jMenu44;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem51;
    private javax.swing.JMenuItem jMenuItem52;
    private javax.swing.JMenuItem jMenuItem53;
    private javax.swing.JMenuItem jMenuItem54;
    private javax.swing.JMenuItem jMenuItem55;
    private javax.swing.JMenuItem jMenuItem56;
    private javax.swing.JMenuItem jMenuItem57;
    private javax.swing.JMenuItem jMenuItem58;
    private javax.swing.JMenuItem jMenuItem59;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem60;
    private javax.swing.JMenuItem jMenuItem61;
    private javax.swing.JMenuItem jMenuItem62;
    private javax.swing.JMenuItem jMenuItem63;
    private javax.swing.JMenuItem jMenuItem64;
    private javax.swing.JMenuItem jMenuItem65;
    private javax.swing.JMenuItem jMenuItem66;
    private javax.swing.JMenuItem jMenuItem67;
    private javax.swing.JMenuItem jMenuItem68;
    private javax.swing.JMenuItem jMenuItem69;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem70;
    private javax.swing.JMenuItem jMenuItem71;
    private javax.swing.JMenuItem jMenuItem72;
    private javax.swing.JMenuItem jMenuItem73;
    private javax.swing.JMenuItem jMenuItem74;
    private javax.swing.JMenuItem jMenuItem75;
    private javax.swing.JMenuItem jMenuItem76;
    private javax.swing.JMenuItem jMenuItem77;
    private javax.swing.JMenuItem jMenuItem78;
    private javax.swing.JMenuItem jMenuItem79;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem80;
    private javax.swing.JMenuItem jMenuItem81;
    private javax.swing.JMenuItem jMenuItem82;
    private javax.swing.JMenuItem jMenuItem83;
    private javax.swing.JMenuItem jMenuItem84;
    private javax.swing.JMenuItem jMenuItem85;
    private javax.swing.JMenuItem jMenuItem86;
    private javax.swing.JMenuItem jMenuItem87;
    private javax.swing.JMenuItem jMenuItem88;
    private javax.swing.JMenuItem jMenuItem89;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu10;
    private java.awt.Menu menu11;
    private java.awt.Menu menu12;
    private java.awt.Menu menu13;
    private java.awt.Menu menu14;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.Menu menu7;
    private java.awt.Menu menu8;
    private java.awt.Menu menu9;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    private java.awt.MenuBar menuBar4;
    private java.awt.MenuBar menuBar5;
    private java.awt.MenuBar menuBar6;
    private java.awt.MenuBar menuBar7;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
